# Fixed-camera trash can configuration.

# Camera
CAMERA_BACKEND = "auto"  # "auto", "opencv", or "picamera2"
CAMERA_SOURCE = 0
CAMERA_CAPTURE_WIDTH = 960
CAMERA_CAPTURE_HEIGHT = 540
FRAME_WIDTH = 640
FRAME_HEIGHT = 360
TARGET_FPS = 30
CAMERA_COLOR_MODE = "bgr"  # "bgr" or "rgb_to_bgr"
SHOW_WINDOW = True
WINDOW_NAME = "Version2TrashCan"
STATUS_PRINT_INTERVAL = 1.0

# Marker and target detection
BLUR_SIZE = (3, 3)
MORPH_KERNEL = (3, 3)
MARKER_DILATE_ITERATIONS = 3
MIN_MARKER_AREA = 3
MAX_MARKER_AREA = 20000
MIN_TARGET_AREA = 180
MAX_TARGET_AREA = 35000
MIN_OBSTACLE_AREA = 300
MAX_OBSTACLE_AREA = 60000
MIN_BOUNDARY_AREA = 500
MAX_BOUNDARY_AREA = FRAME_WIDTH * FRAME_HEIGHT

# HSV ranges are in OpenCV format: H in [0,179], S/V in [0,255].
# Adjust these for your real lighting and tape/object colors.
FRONT_MARKER_HSV_RANGES = (
    # Pink/magenta front marker. Tuned around measured HSV H=135 S=137 V=255.
    ((125, 80, 185), (145, 210, 255)),
)
BACK_MARKER_HSV_RANGES = (
    # Green back marker. Tuned around measured HSV H=77 S=140 V=255.
    ((67, 80, 185), (87, 210, 255)),
)
TARGET_HSV_RANGES = (
    # Tennis ball target. Tuned around measured HSV H=90 S=95 V=255.
    ((88, 45, 185), (104, 155, 255)),
)
OBSTACLE_HSV_RANGES = (
    # White obstacle: bright, low saturation.
    ((0, 0, 180), (179, 55, 255)),
)
BOUNDARY_HSV_RANGES = (
    # White restriction tape: bright, low saturation.
    ((0, 0, 180), (179, 55, 255)),
)

# Target lock behavior
LOCK_ON_FIRST_TARGET = True
LOCK_MAX_JUMP_PX = 90
LOCK_MAX_MISSED_FRAMES = 0
TARGET_COLLECTED_DISTANCE_PX = 45.0
TARGET_COLLECTED_SECONDS = 2.0
RETURN_HOME_WHEN_TARGET_COLLECTED = True
RETURN_HOME_WHEN_TARGET_LOST = False
HOME_STOP_PX = 45.0
KEEP_TRASH_CAN_IN_VIEW = True
VIEW_EDGE_MARGIN_PX = 100
VIEW_SAFE_STOP_PX = 50.0
AVOID_WHITE_OBSTACLES = False
OBSTACLE_PATH_CLEARANCE_PX = 80.0
OBSTACLE_AVOID_OFFSET_PX = 140.0
OBSTACLE_AVOID_FORWARD_PX = 90.0
OBSTACLE_AVOID_SIDE_MULTIPLIERS = (1.0, 1.35, 1.7)
OBSTACLE_AVOID_BLOCKED_GOAL_PENALTY = 500.0
RETURN_HOME_WHEN_OBSTACLE_BLOCKED = True
OBSTACLE_DANGER_DISTANCE_PX = 70.0
ENABLE_WHITE_BOUNDARY = False
BOUNDARY_CLEARANCE_PX = 12
BOUNDARY_PATH_SAMPLE_STEP_PX = 4
BOUNDARY_START_IGNORE_PX = 80
CAN_FOOTPRINT_SHAPE = "square"  # "square" or "circle"
CAN_SQUARE_SIDE_SCALE = 1.4
IGNORE_OBSTACLES_INSIDE_CAN_PX = 95.0
IGNORE_OBSTACLES_CAN_LENGTH_SCALE = 1.4

# Motion/controller behavior
HEADING_ALIGNMENT_DEG = 22.0
FULL_TURN_ANGLE_DEG = 90.0
TURN_STRENGTH_SCALE = 0.70
MIN_TURN_STRENGTH = 20
MAX_TURN_STRENGTH = 75
DISTANCE_STOP_PX = 55.0
FORWARD_ONLY_WHEN_ALIGNED = True
COMMAND_UPDATE_INTERVAL_S = 0.20
COMMAND_CHANGE_CONFIRMATIONS = 3
SWAP_TURN_COMMANDS = True

# Command transport
COMMAND_TRANSPORT = "pi_bluetooth"  # "stdout", "serial", "bluetooth", "gpio", "tcp", or "pi_bluetooth"
SERIAL_PORT = "/dev/ttyUSB0"
SERIAL_BAUDRATE = 9600
SERIAL_TIMEOUT_S = 0.25
BLUETOOTH_DEVICE_NAME = "Version2TrashCan"
BLUETOOTH_MAC_ADDRESS = "D0:EF:76:44:84:52"
BLUETOOTH_CHANNEL = 1
BLUETOOTH_CONNECT_TIMEOUT_S = 8.0
GPIO_LEFT_IN1 = 25
GPIO_LEFT_IN2 = 26
GPIO_RIGHT_IN1 = 27
GPIO_RIGHT_IN2 = 14
GPIO_LEFT_ENABLE = 13
GPIO_RIGHT_ENABLE = 12
GPIO_PWM_FREQUENCY_HZ = 1000
GPIO_DRIVE_DUTY = 100
GPIO_TURN_MIN_DUTY = 60
GPIO_TURN_MAX_DUTY = 100
MOTOR_SERVER_HOST = "motorpi.local"
MOTOR_SERVER_PORT = 4620
MOTOR_SERVER_CONNECT_TIMEOUT_S = 5.0
MOTOR_BLUETOOTH_ADDRESS = "88:A2:9E:6D:D4:A7"
MOTOR_BLUETOOTH_CHANNEL = 1
MOTOR_BLUETOOTH_CONNECT_TIMEOUT_S = 8.0

# Supported commands
CMD_FORWARD = "F"
CMD_LEFT = "L"
CMD_RIGHT = "R"
CMD_STOP = "S"
