# Configuration parameters for auto trash can vision pipeline

# camera geometry
CAMERA_FACING_UP = True

# camera settings
CAMERA_BACKEND = "picamera2"  # "auto", "opencv", or "picamera2"
CAMERA_MODEL = "OV5647 5MP 1080p"
CAMERA_SOURCE = 0  # camera index for USB/Webcam when using the OpenCV backend
CAMERA_CAPTURE_WIDTH = 960
CAMERA_CAPTURE_HEIGHT = 540
CAMERA_VIEW_WIDTH = 1280
CAMERA_VIEW_HEIGHT = 720
FRAME_WIDTH = 480
FRAME_HEIGHT = 270
TARGET_FPS = 60
CAMERA_VIEW_SHARPEN = False
CAMERA_VIEW_SHARPEN_SIGMA = 1.2
CAMERA_VIEW_SHARPEN_AMOUNT = 1.6

# detector settings
FAST_COLOR_DETECTION = True

# motion detector settings
MOG_HISTORY = 120
MOG_VAR_THRESHOLD = 40
MOG_DETECT_SHADOWS = False
MOG_LEARNING_RATE = 0.03
MOTION_WARMUP_FRAMES = 20
BLUR_SIZE = (7, 7)
THRESHOLD_VALUE = 45
TARGET_MASK_THRESHOLD = 80
MORPH_KERNEL = (3, 3)
MOTION_MORPH_KERNEL = (5, 5)
TARGET_DILATE_ITERATIONS = 2
MIN_CONTOUR_AREA = 250
MAX_CONTOUR_AREA = 35000
ASPECT_RATIO_MIN = 0.3
ASPECT_RATIO_MAX = 2.5
MAX_CANDIDATES = 4
SEARCH_TOP_RATIO = 0.05
SEARCH_BOTTOM_RATIO = 0.95
EDGE_IGNORE_PX = 0
EDGE_PENALTY_MARGIN_PX = 24
TARGET_HSV_RANGES = (
    ((18, 90, 80), (38, 255, 255)),
)
MIN_TARGET_PIXELS = 40
MIN_TARGET_RATIO = 0.015
MIN_MOTION_PIXELS = 8
MIN_MOTION_OVERLAP_RATIO = 0.01

# tracking settings
TRACK_HISTORY = 20
TRACK_LOST_MAX_FRAMES = 4
MIN_TRACK_POINTS = 3
MAX_TRACK_JUMP_PX = 180
TARGET_LOCK_BONUS = 2500.0
TARGET_MIN_LOCK_FRAMES = 4
TARGET_REACQUIRE_COOLDOWN_FRAMES = 6
TARGET_STABLE_MAX_STEP_PX = 90
TARGET_STABLE_MAX_AREA_RATIO = 2.2
TARGET_AREA_CHANGE_PENALTY = 1800.0
TARGET_AREA_CHANGE_MAX_RATIO = 1.8
TRACK_LOCKED_MIN_IOU = 0.02
TRACK_LOCKED_MAX_CENTER_DRIFT_PX = 190
TRACK_LOCKED_MAX_ASPECT_RATIO_CHANGE = 2.3
TRACK_LOCKED_IOU_BONUS = 1400.0
TRACK_LOCKED_DISTANCE_PENALTY = 0.75

# prediction settings
CENTER_DEADZONE_PX = 70
OVERHEAD_CENTER_RADIUS_PX = 55
OVERHEAD_AXIS_DEADZONE_PX = 85
OVERHEAD_ALIGN_ANGLE_DEG = 38.0
OVERHEAD_REVERSE_ENABLED = True
OVERHEAD_FRONT_IS_NEGATIVE_Y = False
OVERHEAD_STOP_Y_OFFSET_PX = -90
OVERHEAD_STOP_Y_TOLERANCE_PX = 45
OVERHEAD_TARGET_HOLD_S = 10.0
OVERHEAD_APPROACH_MIN_SPEED_SCALE = 0.35
OVERHEAD_APPROACH_SLOWDOWN_RADIUS_PX = 220
OVERHEAD_ARC_TURN_MIN_STRENGTH = 0.12
OVERHEAD_ARC_TURN_MAX_STRENGTH = 0.55
OVERHEAD_SOFT_ALIGN_ZONE_PX = 135
OVERHEAD_PIVOT_TURN_THRESHOLD_PX = 190
OVERHEAD_PIVOT_TURN_MIN_STRENGTH = 0.25
OVERHEAD_PIVOT_TURN_MAX_STRENGTH = 0.65
MOVE_SCALE = 1.0  # scalar for speed command
MIN_TURN_STRENGTH = 0.35
MAX_TURN_STRENGTH = 1.0
TURN_FORWARD_BIAS = 0.35
COMMAND_UPDATE_INTERVAL_S = 0.12
COMMAND_HOLD_FRAMES = 3
APPROACH_ALIGNED_ONLY = True
TARGET_CLOSE_Y_RATIO = 0.72
TARGET_CLOSE_AREA = 18000
TARGET_STOP_X_DEADZONE_PX = 30
PATH_GUIDE_LOOKAHEAD_RATIO = 0.35
PATH_TURN_CLOSE_RATIO = 0.18
PATH_MIN_TURN_STRENGTH = 0.45
MOTOR_MOCK = False
MOTOR_DRIVER = "l298n"
L298N_LEFT_ENABLE_PIN = 13
L298N_LEFT_IN1_PIN = 5
L298N_LEFT_IN2_PIN = 6
L298N_RIGHT_ENABLE_PIN = 18
L298N_RIGHT_IN3_PIN = 23
L298N_RIGHT_IN4_PIN = 24
L298N_PWM_FREQUENCY = 1000
MOTOR_FORWARD_DUTY = 0.8
MOTOR_REVERSE_DUTY = 1
MOTOR_TURN_DUTY = 1
VISUAL_TURN_MAX_STRENGTH = 0.55
LEFT_MOTOR_SCALE = 1.0
RIGHT_MOTOR_SCALE = 1.0
# Motor tuning notes for real hardware:
# - Increase MOTOR_FORWARD_DUTY if the robot does not move or feels too slow.
# - Increase MOTOR_REVERSE_DUTY if reverse just hums or buzzes instead of rolling backward.
# - Decrease MOTOR_FORWARD_DUTY if the robot moves too fast or overshoots.
# - Increase MOTOR_TURN_DUTY if turns are too weak or too slow.
# - Decrease MOTOR_TURN_DUTY if turns are too sharp, jerky, or unstable.
# - Reduce LEFT_MOTOR_SCALE or RIGHT_MOTOR_SCALE if one side consistently runs faster.
# - Set LEFT_MOTOR_INVERTED or RIGHT_MOTOR_INVERTED to True if that side spins backward when forward is expected.
# This project does not use a separate motor calibration file; these config values are the main adjustment points.
LEFT_MOTOR_INVERTED = False
RIGHT_MOTOR_INVERTED = True

# visual / behavior flags
DEBUG_DRAW = False
SHOW_FPS = True
SHOW_WINDOW = True
STATUS_PRINT_INTERVAL = 2.0

# convenience
WINDOW_NAME = "AutoTrashCan Vision"
